function Hd = myfilter2
%MYFILTER2 Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 25.1 and Signal Processing Toolbox 25.1.
% Generated on: 27-Nov-2025 14:12:07

% FIR constrained least-squares Bandstop filter designed using the FIRCLS
% function.

% All frequency values are in Hz.
Fs = 44100;  % Sampling Frequency

N       = 10;    % Order
Fc1     = 500;   % First Cutoff Frequency
Fc2     = 3500;  % Second Cutoff Frequency
Dpass1U = 0.1;   % Upper Passband Ripple
Dpass1L = 0.1;   % Lower Passband Ripple
DstopU  = 0.1;   % Upper Stopband Attenuation
DstopL  = 0.1;   % Lower Stopband Attenuation
Dpass2U = 0.1;   % Upper Passband Ripple
Dpass2L = 0.1;   % Lower Passband Ripple

% Calculate the coefficients using the FIRCLS function.
b  = fircls(N, [0 Fc1 Fc2 Fs/2]/(Fs/2), [1 0 1], [1+Dpass1U DstopU ...
            1+Dpass2U], [1-Dpass1L -DstopL 1-Dpass2L]);
Hd = dfilt.dffir(b);

% [EOF]
