function Hd = myfilter4
%MYFILTER4 Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 25.1 and Signal Processing Toolbox 25.1.
% Generated on: 27-Nov-2025 14:22:09

% FIR constrained least-squares Bandpass filter designed using the FIRCLS
% function.

% All frequency values are in Hz.
Fs = 44100;  % Sampling Frequency

N       = 10;    % Order
Fc1     = 1360;  % First Cutoff Frequency
Fc2     = 2735;  % Second Cutoff Frequency
Dstop1U = 0.1;   % Upper Stopband Attenuation
Dstop1L = 0.1;   % Lower Stopband Attenuation
DpassU  = 0.1;   % Upper Passband Ripple
DpassL  = 0.1;   % Lower Passband Ripple
Dstop2U = 0.1;   % Upper Stopband Attenuation
Dstop2L = 0.1;   % Lower Stopband Attenuation

% Calculate the coefficients using the FIRCLS function.
b  = fircls(N, [0 Fc1 Fc2 Fs/2]/(Fs/2), [0 1 0], [Dstop1U 1+DpassU ...
            Dstop2U], [-Dstop1L 1-DpassL -Dstop2L]);
Hd = dfilt.dffir(b);

% [EOF]
