function Hd = myfilter3
%MYFILTER3 Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 25.1 and Signal Processing Toolbox 25.1.
% Generated on: 27-Nov-2025 14:14:19

% FIR constrained least-squares Highpass filter designed using the FIRCLS
% function.

% All frequency values are in Hz.
Fs = 44100;  % Sampling Frequency

N      = 10;    % Order
Fc     = 3000;  % Cutoff Frequency
DstopU = 0.1;   % Upper Stopband Attenuation
DstopL = 0.1;   % Lower Stopband Attenuation
DpassU = 0.1;   % Upper Passband Ripple
DpassL = 0.1;   % Lower Passband Ripple

% Calculate the coefficients using the FIRCLS function.
b  = fircls(N, [0 Fc Fs/2]/(Fs/2), [0 1], [DstopU 1+DpassU], [-DstopL ...
            1-DpassL]);
Hd = dfilt.dffir(b);

% [EOF]
